repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-json
      - id: pretty-format-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: flake8
        args:
          [
            "--max-line-length=120",
            "--ignore=E722, W503, F403, F405",
            "--exclude=*/migrations/*",
          ]
        language: python
  - repo: https://github.com/prettier/prettier
    rev: 1.17.0
    hooks:
      - id: prettier
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6
        exclude: migrations|monitest/|manage.py
